spring:
  application:
    name: Votify
  datasource:
    url: jdbc:postgresql://localhost:1225/votify
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

election:
  jwt:
    secret: electionVerySecretKeyAndItHasToKeepToBe0001
    expiration: 86400000